### ISSUE TITLE
Google Chrome Issue

### ISSUE THREAD

**Issue by brunocalado** [bekriebel/fvtt-module-avclient-livekit#46]
Hii

I'm having a problem with Google Chrome for sometime. Some players just can't conect to livekit using Google Chrome. Changing to Edge solves the problem.
![image](https://user-images.githubusercontent.com/4999783/225431935-ae970403-889d-42b5-a46b-5d67606efc76.png)

To try to solve the problem I:
- google chrome anonymous tab 
- remove Google folder C:\Users\myuser\AppData\Local\Google
This solved for some players, but not for others.

Is there some tip to help it work on chrome?

tks

**Comment by igorteuri** [comment]
I'm having the same problem here.

**Comment by bekriebel** [comment]
Hrmm... I just tested against my cluster with Chrome v111.0.5563.65 on Windows and it seems to be working fine. This seems like either a configuration issue, or a Chrome issue. Are these new installations that have never worked, were any updates done, or did this just start happening with no changes to your LiveKit install?

**Comment by brunocalado** [comment]
> 

They worked for a time. Then, this started to happen with some of my players. I happened once with me, I deleted google data folder and solved.

**Comment by bekriebel** [comment]
Hrmm... this sounds like it may be either a chrome or LiveKit issue, then. It may be worth checking the Chrome bug tracker or check on LiveKit's support Slack to see if there is any known issue. I haven't had any reports of a similar issue against my Patreon cluster, so it may be version specific to LiveKit as well.

**Comment by mathsteck** [comment]
Yesterday I also had the exactly same issue with one of my players. Everyone using Chrome but one particular player couldn't join the A/V.

![image](https://user-images.githubusercontent.com/3390366/226447950-55ddbf58-37ae-41fe-85bc-ac6f85e35130.png)

**Comment by brunocalado** [comment]
Use https://flc.ruleplaying.com/ helps.

Em qua, 31 de mai de 2023 12:43, Jaime Mendes ***@***.***>
escreveu:

**Comment by bekriebel** [comment]
It is still maintained, but I have yet to be able to reproduce the issue. It seems to be fixed by clearing data in google chrome or sometimes using an incognito mode tab. This makes me think it's something specific with browser configuration. If anyone has more details to add to help me reproduce, I can see if there's any workaround to be done.

**Comment by mathsteck** [comment]
I might have some logs that can be useful:

`livekit-client.esm.mjs:19630 WebSocket connection to 'wss://voicelocaweb.duckdns.org/rtc?access_token=eyJhbGciOiJIUzI1NiJ9.eyJ2aWRlbyI6eyJyb29tSm9pbiI6dHJ1ZSwicm9vbSI6Im9sRFZ5VUJvZlUxbjZBWmRoYTM1aGdwaVVaaDFoQVFDIn0sIm1ldGFkYXRhIjoie1wiZnZ0dFVzZXJJZFwiOlwiSEQ4OHNMd1R3Sng1N252Z1wiLFwidXNlRXh0ZXJuYWxBVlwiOmZhbHNlfSIsImlzcyI6IkFQSWFpb0xvZ2FLWUUyNCIsImV4cCI6MTY4NTcyNjcyOCwianRpIjoiTWF0aGV1cyIsInN1YiI6Ik1hdGhldXMiLCJuYmYiOjE2ODU2ODk4Mjh9.BuzBhExm9vGKqhzNuOCN-R4A3Wdut_BiIHFB_ixQMcI&auto_subscribe=1&sdk=js&version=1.8.0&protocol=9&adaptive_stream=1' failed: 
(anonymous) @ livekit-client.esm.mjs:19630
foundry.js:67285 Disconnected from LiveKit A/V Server
fetch @ foundry.js:67285
LiveKitAVClient.ts:351 LiveKitAVClient | Could not connect: Error: could not establish signal connection: Internal error
    at Ma.attemptConnection (livekit-client.esm.mjs:22243:32)
    at async s (livekit-client.esm.mjs:22133:9)
    at async Jr.promise.Promise.finally.e (livekit-client.esm.mjs:15178:11)
connect @ LiveKitAVClient.ts:351
foundry.js:67285 Error connecting to LiveKit Server: could not establish signal connection: Internal error
fetch @ foundry.js:67285
foundry.js:90703 Foundry VTT | Activating pending audio playback with user gesture.
56 log entries are not shown.`

**Comment by bekriebel** [comment]
This may not be everyone's issue, but for this log in particular it is almost certainly the use of duckdns combined with ad blockers. For some reason, ad blockers seem to block all webrtc connections to duckdns domains. I have a warning about that on the README: https://github.com/bekriebel/fvtt-module-avclient-livekit#running-your-own-livekit-server

> I might have some logs that can be useful:
> 
> [LivekitChromeError.log](https://github.com/bekriebel/fvtt-module-avclient-livekit/files/11633015/LivekitChromeError.log)

**Comment by theripper93** [comment]
Something seems to have changed recently with adblockers , chrome, duckdins or a mix of them - disabling adblockers on the page fixed it for me. This problem started apparently randomly, never had duckdns issues before 2\3 days ago

**Comment by bekriebel** [comment]
> Something seems to have changed recently with adblockers , chrome, duckdins or a mix of them - disabling adblockers on the page fixed it for me. This problem started apparently randomly, never had duckdns issues before 2\3 days ago

It may be intermittent based on whatever rules are in place with the blockers at any given time, but it's been a recurring problem for some time.

**Comment by bekriebel** [comment]
A major refactor has been done for FoundryVTT v13 support. Please re-open if this continues to be an issue with the latest released version.
